### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Htebib89** [Oxalide/vsphere-influxdb-go#104]
Hello,

I've setup the poject and it runs correctly  for over 6 months, but the last week the projct stop to retrieve the data from vcenter and i receive this error when i run the project :

goroutine 6 [running]:
main.(*VCenter).Query(0xc42006a8c0, 0xc4200e07a0, 0x1, 0x4, 0xc4200ee180, 0x1, 0x4, 0x3c, 0xc42006f3b0, 0xb, ...)
        /home/vikram/Projects/mine/GO_HOME/src/github.com/vikramjakhr/vsphere-vcenter-influx-go/vsphere-influxdb.go:512 +0x4d3c
main.worker(0x3, 0xc4200e07a0, 0x1, 0x4, 0xc4200ee180, 0x1, 0x4, 0x3c, 0xc42006f3b0, 0xb, ...)
        /home/vikram/Projects/mine/GO_HOME/src/github.com/vikramjakhr/vsphere-vcenter-influx-go/vsphere-influxdb.go:900 +0x42d
created by main.main
        /home/vikram/Projects/mine/GO_HOME/src/github.com/vikramjakhr/vsphere-vcenter-influx-go/vsphere-influxdb.go:1023 +0x9c3

Could you please help?
Many thanks.

Haithem Tebib
Best Regards,

**Comment by sofixa** [comment]
Hi @Htebib89 , was your vCenter/ESXi fully accessible when it crashed? Has something changed ( update, certificate change, etc. ) ?
