### ISSUE TITLE
Help on initial setup

### ISSUE THREAD

**Issue by pr-acassera** [Oxalide/vsphere-influxdb-go#36]
I am using go 1.8
I wanted to know what might be happening.  This is against vcenter 6.0.  I just wanted to see if I could connect and grab some statistics, influxdb is 1.3.

I get the following:

2017/09/21 15:23:07 Starting : vsphere-influxdb-go
2017/09/21 15:23:07 ---Configuration - you should see the config here---
(main.Configuration) {
 VCenters: ([]*main.VCenter) (len=1 cap=4) {
  (*main.VCenter)(0xc4200547d0)({
   Hostname: (string) (len=20) "vcenter.lab.com",
   Username: (string) (len=17) "govc@lab.com",
   Password: (string) (len=9) "vcpass",
   MetricGroups: ([]*main.MetricGroup) <nil>
  })
 },
 Metrics: ([]main.Metric) (len=4 cap=4) {
  (main.Metric) {
   ObjectType: ([]string) (len=2 cap=4) {
    (string) (len=14) "VirtualMachine",
    (string) (len=10) "HostSystem"
   },
   Definition: ([]main.MetricDef) (len=1 cap=4) {
    (main.MetricDef) {
     Metric: (string) (len=17) "cpu.usage.average",
     Instances: (string) (len=1) "*",
     Key: (int32) 0
    }
   }
  },
  (main.Metric) {
   ObjectType: ([]string) (len=1 cap=4) {
    (string) (len=14) "VirtualMachine"
   },
   Definition: ([]main.MetricDef) (len=1 cap=4) {
    (main.MetricDef) {
     Metric: (string) (len=19) "cpu.ready.summation",
     Instances: (string) (len=1) "*",
     Key: (int32) 0
    }
   }
  },
  (main.Metric) {
   ObjectType: ([]string) (len=1 cap=4) {
    (string) (len=10) "HostSystem"
   },
   Definition: ([]main.MetricDef) (len=1 cap=4) {
    (main.MetricDef) {
     Metric: (string) (len=27) "disk.capacity.usage.average",
     Instances: (string) "",
     Key: (int32) 0
    }
   }
  },
  (main.Metric) {
   ObjectType: ([]string) (len=1 cap=4) {
    (string) (len=9) "Datastore"
   },
   Definition: ([]main.MetricDef) (len=1 cap=4) {
    (main.MetricDef) {
     Metric: (string) (len=22) "datastore.read.average",
     Instances: (string) (len=1) "*",
     Key: (int32) 0
    }
   }
  }
 },
 Interval: (int) 60,
 Domain: (string) (len=13) ".lab.com",
 InfluxDB: (main.InfluxDB) {
  Hostname: (string) (len=24) "http://192.168.2.12:8086",
  Username: (string) (len=2) "vm",
  Password: (string) (len=8) "password",
  Database: (string) (len=18) "vmware-performance"
 }
}
2017/09/21 15:23:07 connecting to vcenter: vcenter.lab.com
2017/09/21 15:23:07 Successfully connected to Influx
2017/09/21 15:23:07 Querying vcenter
2017/09/21 15:23:07 Setting up query inventory of vcenter:  vcenter.lab.com
2017/09/21 15:23:07 connecting to vcenter: vcenter.lab.com
([]types.ManagedObjectReference) (len=5 cap=5) {
 (types.ManagedObjectReference) Datastore:datastore-10,
 (types.ManagedObjectReference) ResourcePool:resgroup-8,
 (types.ManagedObjectReference) HostSystem:host-9,
 (types.ManagedObjectReference) VirtualMachine:vm-13,
 (types.ManagedObjectReference) VirtualMachine:vm-12
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9177cc]

goroutine 1 [running]:
github.com/vmware/govmomi/property.(*Collector).Retrieve(0xc4204f20b0, 0x102a0a0, 0xc4203d4640, 0x1071940, 0x0, 0x0, 0xc4201d0570, 0x3, 0x3, 0x9b3b00, ...)
	/usr/local/go/src/github.com/vmware/govmomi/property/collector.go:157 +0x50c
main.(*VCenter).Query(0xc4204f7ad0, 0xc4200c4940, 0x1, 0x4, 0xc4200d2180, 0x4, 0x4, 0x3c, 0xc420013420, 0xd, ...)
	/root/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:300 +0x2bb4
main.queryVCenter(0xc4200c49c0, 0x14, 0xc4200c49a0, 0x11, 0xc4200134b0, 0x9, 0xc420424520, 0x3, 0x4, 0xc4200c4940, ...)
	/root/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:738 +0x126
main.main()
	/root/go/src/github.com/oxalide/vsphere-influxdb-go/vsphere-influxdb.go:808 +0x907

**Comment by pr-acassera** [comment]
I reconfigured using the original developer code vsphere-graphite.
